import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {ThemeProvider} from 'next-themes';
import ThemeChanger from '@/components/ThemeChanger';
import Background from '@/components/Background';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            suppressHydrationWarning>
            <head>
                <link
                    rel='preconnect'
                    href='https://fonts.googleapis.com'
                />
                <link
                    rel='preconnect'
                    href='https://fonts.gstatic.com'
                />
                <link
                    href='https://fonts.googleapis.com/css2?family=Barriecito&family=Lacquer&display=swap'
                    rel='stylesheet'
                />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black`}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='light'>
                    {/* <ThemeChanger/> */}
                    <Background />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
